-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)

CREATE TABLE IF NOT EXISTS hcps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    specialty VARCHAR(255) NOT NULL DEFAULT 'General Medicine',
    hospital VARCHAR(255) NOT NULL DEFAULT 'Unknown Hospital',
    chat_thread_id VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT _hcp_tenant_unique_combo UNIQUE (tenant_id, name, specialty, hospital)
);

CREATE INDEX IF NOT EXISTS idx_hcps_tenant_id ON hcps (tenant_id);
CREATE INDEX IF NOT EXISTS idx_hcps_chat_thread_id ON hcps (chat_thread_id);

CREATE TABLE IF NOT EXISTS interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hcp_id BIGINT NOT NULL REFERENCES hcps(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL,
    product_discussed VARCHAR(100),
    meeting_notes TEXT NOT NULL,
    sentiment VARCHAR(50),
    interaction_outcome TEXT,
    follow_up_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_interactions_tenant_id ON interactions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_interactions_hcp_id ON interactions (hcp_id);
